version: '3.9'
services:
  langserve:
    image: langserve:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    env_file:
      - .env